apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jbm6ek0uv-nodejs
  janus-idp.io/tekton: jbm6ek0uv-nodejs
  backstage.io/kubernetes-id: jbm6ek0uv-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jbm6ek0uv-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
