apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jbm6ek0uv-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jbm6ek0uv-nodejs 
  name: jbm6ek0uv-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: jbm6ek0uv-nodejs 
